import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is hand-grouped around how the platform is built.
 *
 * URLs follow the file path under `docs/` one-to-one (no `slug` front matter),
 * so a document's location on disk is always its location on the site. The
 * grouping below is the only place where the Core / Products / Company / Guides
 * taxonomy lives.
 *
 * Sub-folders stay autogenerated so a new page is picked up without editing
 * this file; only the top-level grouping is explicit. Category metadata for a
 * top-level group lives here, not in `_category_.json`, so there is a single
 * place to look. Nested folders (`vtual/app`, `vtual/app/account-manager`,
 * `vtual/app/simp`) keep their own `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Products',
      items: [
        {
          type: 'category',
          label: 'vTual',
          link: {
            type: 'generated-index',
            description:
              'Everything you need to get the most out of vTual, from the home page to your account settings.',
          },
          items: [{type: 'autogenerated', dirName: 'vtual'}],
        },
        {
          type: 'category',
          label: 'Archivd',
          link: {
            type: 'generated-index',
            description:
              'Your personal drive, link sharing, and the team workspaces that Archivd adds on top.',
          },
          items: [{type: 'autogenerated', dirName: 'archivd'}],
        },
        {
          type: 'category',
          label: 'Microstock',
          link: {
            type: 'generated-index',
            description:
              'Turn a folder of images into marketplace-ready metadata, from upload to export.',
          },
          items: [{type: 'autogenerated', dirName: 'microstock'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Core',
      items: [
        {type: 'autogenerated', dirName: 'legal'},
        {type: 'autogenerated', dirName: 'account'},
        {type: 'autogenerated', dirName: 'billing'},
        'notifications',
        'pembayaran-dan-perpajakan',
      ],
    },
    {
      type: 'category',
      label: 'Company',
      items: ['silverspoon/contact', 'silverspoon/domain'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guide/disposable-email'],
    },
  ],
};

export default sidebars;
